### ISSUE TITLE
CSV as Table widget overwrites columns with same header

### ISSUE THREAD

**Issue by lrporder** [ArjenLammers/oqlmodule#14]
The CSV as Table widget overwrites values in the first column with the same header name, when there are multiple columns with the same header.
Try for example the following query in the _USE_ME/OQL snippet and compare table with downloaded file:
```sql
SELECT entity/Name, reference/Name
FROM MxModelReflection.MxObjectType entity
INNER JOIN entity/MxModelReflection.MxObjectReference_MxObjectType_Parent/MxModelReflection.MxObjectReference reference
WHERE entity/Module = 'MxModelReflection' AND entity/Name = 'MxObjectType'
```

Workaround is to add different aliases in the SELECT part, like SELECT entity/Name AS entName, reference/Name AS refName.

**Comment by ArjenLammers** [comment]
I was able to reproduce this.
It is due to how the CSVAsTable widget treats data; based on column name, which is duplicate in this case.
Download of the data will still give a valid CSV though.

On the other hand; it is quite in line with the module's behavior regarding OQL mappings to objects, where duplicate column names (= attribute) isn't possible either. 
Maybe I will fix it in a future release.
